# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'airapps' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for airapps
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'ART',
    'RCTActionSheet',
    'RCTGeolocation',
    'RCTImage',
    'RCTNetwork',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'RCTLinkingIOS',
    'RCTAnimation',
    'RCTAdSupport',
    'RCTCameraRoll',
    'RCTPushNotification',
    'RCTSettings'
  ]
  pod 'PLMediaStreamingKit'
  pod 'PLPlayerKit'
  pod 'AMap3DMap'  #3D地图SDK
  #pod 'AMap2DMap' #2D地图SDK (2D和3D不能同时使⽤用)
  pod 'AMapSearch' #搜索服务SDK
  pod 'RCTPili', :path => '../node_modules/react-native-pili/ios/RCTPili'
  pod 'UMengAnalytics-NO-IDFA'
  pod 'airumeng', :path => '../node_modules/air-umeng/ios/airumeng'
  pod 'RCTRongCloud', :path => '../node_modules/air-rongcloud/ios'
  pod 'RNSVG', :path => '../node_modules/react-native-svg'
  pod 'RCTAMap', :path => '../node_modules/air-amap/ios'
  pod 'RCTWeChat', :path => '../node_modules/react-native-wechat/ios'
  #pod 'ReactNativeConfig', :path => '../js/node_modules/react-native-config/ios'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'RNFS', :path => '../node_modules/react-native-fs'
  target 'airappsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
